name: Feature request
description: Suggest an improvement
title: 'feat: '
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
